name: FutureMyNotes
description: My notes for cell phones in flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:

  path_provider: ^2.0.8
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  image_picker: ^0.8.4+8
  json_annotation: ^4.0.1
  contactus: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.0.4
  json_serializable: ^4.1.3

flutter_icons:
  android: true
  ios: true
  image_path: "src/img/logo.png"

flutter:
  uses-material-design: true

  assets:
    - src/img/logo.png
    - src/img/gerb.png
    - src/img/milytary_anime.png
    - src/img/rusian_fack_you.png
    - src/img/dev_image.jpg


